### ISSUE TITLE
Re-evaluate BUIC vars

### ISSUE THREAD

**Issue by aruniverse** [iTwin/appui#241]
We have about ~500 hits for BUIC vars within the AppUI repo 

<img width="266" alt="image" src="https://user-images.githubusercontent.com/11051042/229183786-1fdc57e8-c3fe-4b4c-a20d-93d6c4b9f3aa.png">

In 4.0, we switched to using iTwinUI vars, and most of these BUIC vars are aliases for iTwinUI vars.
Does having both BUIC and iTwinUI vars add confusion? If so, remove all BUIC vars in a new major, and just use iTwinUI all the way through
```[tasklist]
### Tasks
- [ ] Change scss from `var(--buic` to `var(--iui` (Non breaking) (134 hits)
- [ ] Remove `--buic` vars (**Breaking**) (85 hits)
- [ ] Reduce number of `$buic-` sass variables (**breaking**) (91 hits)
```

**Comment by GerardasB** [comment]
Duplicate of https://github.com/iTwin/appui/issues/958
