### ISSUE TITLE
Explore storybook like integration

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#354]
We would like to have a way to present fine grain interactive examples and validation of our components and API (hooks).

Storybook is the goto solution for this, but there might be other alternatives, one suggestion being http://ladle.dev.

Thigs to take into consideration: 
We are depending on iTwin.js which require some tweaking for the bundler, we need to ensure that these are either doable in this tool, or that we dont need them at all to test our components. (iTwin Studio is using Vite at the moment and can handle iTwin.js bundling, so if it does not work out of the box, maybe look their solutions)

We would also like to be deploying to github pages which was enabled for appui repo, and possibly deploy PR's so the result can be validated directly. (Similar to iTwinUI)

```[tasklist]
### Tasks
- [ ] Configure `storybook-like` solution in repository
- [ ] Deploy "release" version in github pages
- [ ] Deploy "pr" version in github pages
```

**Comment by GerardasB** [comment]
Storybook based on a `main` branch: https://itwin.github.io/appui/storybook/
