### ISSUE TITLE
Explore current popouts limitations

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#364]
Our current implementation does not work when the application is within an `iframe`, we need to validate what are the general limitations of popouts "normal" use and also within an iFrame as this is used by internal Bentley applications

```[tasklist]
### Tasks
- [ ] https://github.com/iTwin/appui/issues/379
- [ ] https://github.com/iTwin/appui/issues/383
- [ ] https://github.com/iTwin/appui/issues/384
- [ ] https://github.com/iTwin/appui/issues/202
- [ ] https://github.com/iTwin/appui/issues/273
- [ ] https://github.com/iTwin/appui/issues/380
- [ ] https://github.com/iTwin/appui/issues/381
- [ ] https://github.com/iTwin/appui/issues/402
- [ ] https://github.com/iTwin/appui/issues/498
- [ ] https://github.com/iTwin/appui/issues/494
- [ ] https://github.com/iTwin/appui/issues/536
- [ ] https://github.com/iTwin/appui/issues/524
- [ ] https://github.com/iTwin/appui/issues/563
- [ ] https://github.com/iTwin/appui/issues/564
- [ ] https://github.com/iTwin/appui/issues/612
- [ ] https://github.com/iTwin/appui/issues/627
- [ ] https://github.com/iTwin/appui/issues/632
- [ ] https://github.com/iTwin/appui/issues/649
- [ ] https://github.com/iTwin/appui/issues/650
- [x] Multiple react element trees can not share root context providers. Investigate using the portaling instead. https://github.com/iTwin/appui/pull/820
```

**Comment by raplemie** [comment]
Electron exploration still needed
