### ISSUE TITLE
Update learning documentation

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#573]
Documentation is lagging behind in part because the images and code snippets become obsolete. We should rework the content and could use storybook and/or extracted code snippets from test apps or storybook itself to display example and visuals
```[tasklist]
### Tasks
- [ ] https://github.com/iTwin/appui/issues/578
- [x] Match breadcrumb titles with page titles
- [x] Use expandable container for code snippets
```
