### ISSUE TITLE
Move to `vite`

### ISSUE THREAD

**Issue by raplemie** [iTwin/appui#585]
We are using `@bentley/react-scripts` which is based on create react app, however this way of building apps have been dropped by React and is no longer recommended.

`vite` appear to be the goto solution and is already used in core and studio, so we should probably create a test app using vite in the first time to validate that everything works correctly, and in a second phase probably retire the current cra based test apps.

Using `vitest` might also help us with up to date testing solution rather than mocha which is getting old and makes testing with iTwinUI difficult.

```[tasklist]
### Tasks
- [x] Create `vite` based test apps
- [ ] Explore `vitest` as a replacement for `mocha`
- [x] Remove `cra` based test apps.
```
