### ISSUE TITLE
Update release tags of frequently used APIs

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#891]
```[tasklist]
### Tasks
- [x] `AccuDrawKeyboardShortcuts` will be bumped to `@public`
- [x] `DrawingNavigationAidControl` will be bumped to `@public`, although it will be deprecated as well https://github.com/iTwin/appui/pull/888
- [x] `ReducerRegistry` will be bumped to `@public` and is deprecated already.
- [x] `@internal` tag will be removed from `ToolAssistanceField` https://github.com/iTwin/appui/issues/671
- [x] `AccuDrawWidget` will be bumped to `@public`.
- [x] `BackstageItemUtilities`, `StatusBarItemUtilities`, and `ToolbarItemUtilities` will be bumped to `@public`.
- [x] `useTransientState` will be bumped to `@public`.
- [ ] `FormatProps` is from `@itwin/core-quantity` and will be bumped to `@public`.
```
