### ISSUE TITLE
Deprecation remnants for 5.0

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#955]
A list of overlooked APIs that we want to deprecate before 5.0. These are mostly related to already deprecated APIs.

```[tasklist]
### Tasks
- [x] Deprecate `UiFramework.fronstages.clearFrontstageProviders()` (`Ctrl+F` for other non-deprecated `FrontstageProvider` APIs) Make sure it's possible to clear registered frontstages https://github.com/iTwin/appui/pull/1022
- [x] Deprecate APIs that implement `UiItemsProvider`. I.e. `provideStatusBarItems` of `StandardStatusbarUiItemsProvider` should be deprecated and `getStatusBarItems` should be added. https://github.com/iTwin/appui/pull/1024
- [x] `BaseUiItemsProvider` needs to be deprecated as well since we'll have no way to do the arg checks with new provider APIs (classes that extend `BaseUiItemsProvider` need to be deprecated as well) https://github.com/iTwin/appui/pull/1024
- [x] It seems like `ConditionalValue.ts` is not exported in a barrel file. And the changelogs do not mention `ConditionalBooleanValue`, `ConditionalStringValue`, `ConditionalIconValue` addition. Let's remove `ConditionalIconValue` before exporting the module in the barrel. https://github.com/iTwin/appui/pull/1031
- [x] Deprecate `setIsUiVisible` and `getIsUiVisible` of `UiFramework` https://github.com/iTwin/appui/pull/1023
- [x] Review usage of `@itwin/core-react` `Dialog` and `Popup`. Especially look into components that are currently using `DialogProps` and `PopupProps` (components like that should be deprecated). Make sure that we can replace core components with `iTwinUI` `Dialog` and `Popover`.
```
