### ISSUE TITLE
Remove requirement for `ThemeManager`

### ISSUE THREAD

**Issue by GerardasB** [iTwin/appui#958]
### Is your feature request related to a problem? Please describe.

Explicitly wrapping `AppUI` components in `ThemeManager` should not be required.
Investigate what it would take to achieve this.

```[tasklist]
### Tasks
- [x] Replace `AppUI` CSS variables with `iTwinUI` variables. I.e. `--buic-background-1` should be replaced by `var(--iui-color-background);`. #1079
- [x] ~~Deprecate `ThemeManager` **before 5.0**. Make sure that `--buic` continues to work, and v2 iTwinUI Provider might be needed as well~~. Let's keep it until CSS variables are removed.
- [x] Deprecate `--buic` CSS vars (in NextVersion.md, create a mapping table) **before 5.0** https://github.com/iTwin/appui/pull/1029
- [x] Deprecate `$buic-` SCSS variables (in NextVersion.md) **before 5.0** https://github.com/iTwin/appui/pull/1029
```

### Describe the Solution you'd like

`ThemeProvider` of `iTwinUI` should be enough instead of currently used `ThemeManager`.

**Comment by GerardasB** [comment]
Related issue: https://github.com/iTwin/appui/issues/241
